\documentclass[11pt]{article}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb,booktabs,graphicx,hyperref}
\hypersetup{colorlinks=true,allcolors=blue}

\title{Representation Type and Readout Expression\\in Neural Group Composition}
\author{Mohib\\University of Warwick}
\date{August 2026}
% Figures 1-5 are generated by analyse.py from results/*.json. If the results
% have not been produced yet the figure slot renders a note instead, so the
% paper always compiles and never silently ships a stale image.
\newcommand{\genfig}[2]{%
  \IfFileExists{../figs/#1}{\includegraphics[width=#2]{../figs/#1}}%
  {\fbox{\parbox{0.9\textwidth}{\vspace{4mm}\centering
   \texttt{\detokenize{figs/#1}} not present.\par\medskip
   Run \texttt{python analyse.py} to generate it from \texttt{results/}.
   \vspace{4mm}}}}}

\begin{document}
\maketitle

\begin{abstract}
We train one-hidden-layer MLPs to complete the multiplication table of a finite
group, holding group order, dataset size and output cardinality fixed so that
only the algebra varies. We report two findings.

(A) Groups carrying quaternionic-type irreducible representations reach
substantially lower validation accuracy at a fixed data budget and a fixed
training budget than groups that do not, at fixed order. We
test this on the complete population of all fifteen groups of order 24, which
removes any discretion over which groups to include. Ranked by mean final
validation accuracy over twelve independent instances each, the five
quaternionic-type groups are separated from the other ten by a preregistered
exact test at $p = 1/\binom{15}{5} = 3.3\times 10^{-4}$. The sharpest comparison is the
character-table twin: pairs such as $D_8\times\mathbb{Z}_3$ and
$Q_8\times\mathbb{Z}_3$ that share their entire ordinary character table but
differ in Frobenius--Schur indicator, hence in the real structure of their
group algebras ($M_2(\mathbb{R})$ versus $\mathbb{H}$). There are two such
pairs at order 24 and both separate in the predicted direction. A third pair
matched only on irreducible degrees and class sizes, preregistered before it was
trained, separates too.

(B) A frozen hidden layer in $Q_8\times\mathbb{Z}_3$ supports a linear readout
far better than the one the network trained; but how much better is not a
property of the network. Fitting thirty readout configurations to the same
frozen representation --- the same representation, within each seed --- the
reported gap runs from $-0.021$ under a recently published probe protocol to
$+0.235$ under ridge with the regulariser chosen inside the training split, a
range of $0.256$. Holding objective, optimiser, budget and initialisation fixed
and varying only the readout weight decay still moves it from $+0.002$ to
$+0.181$. Under the published protocol the character-table twins do not
separate; under ridge they do ($+0.235$ against $-0.033$). We
argue the linear-probe gap is not well defined without stating the probe's
regularisation.

A factorial over end-to-end and readout weight decay separates two roles that
have been conflated: higher end-to-end weight decay is associated with far
greater linear decodability at a fixed budget (probe accuracy
$0.162 \to 0.992$), while readout weight decay limits how much of it a linear
readout expresses (span $0.146$ at fixed representation).

We state explicitly what is not established, including any causal chain from
Frobenius--Schur type to the readout defect, and the fact that character-table
matching does not isolate the Frobenius--Schur indicator.
\end{abstract}

\section{Introduction}

Grokking --- delayed generalisation long after training loss saturates --- has
been characterised largely in terms of optimisation quantities: weight decay,
learning rate, norm ratios, circuit efficiency \cite{power,nanda,varma}. Recent
work sharpens this. Truong \cite{truong} shows that under cross-entropy the
weight-norm dependence of the delay runs through the effective logit scale
rather than the scalar norm, and Chou et al.\ \cite{chou} decompose networks
into encoder and linear readout and give four diagnostic signatures for grokking
and double descent. The circuit literature on group composition asks which
algorithm forms \cite{chughtai,stander}, not when it forms or why some tasks
resist it. Notsawo et al.\ \cite{notsawo} widen the task family to
finite-dimensional algebras and show that associativity, unitality,
commutativity and structure-tensor statistics affect grokking delay and sample
complexity.

What is largely absent is a controlled variation of the algebraic structure of
the task at fixed cardinality. This is precisely what the finite-dimensional
algebra framework cannot reach within groups of a fixed order: there the
structure tensor is $\mathcal{C}_{ijk} = \mathbb{1}(g_ig_j = g_k)$, whose mode-3
rows have pairwise disjoint supports of size $n$, so $\operatorname{rank}
\mathcal{C}_{(3)} = n$ and the sparsity is $n^2$ for \emph{every} group of that
order. Associativity and unitality hold by the group axioms, and commutativity
agrees within every twin pair. Unfolding rank and canonical-basis sparsity are therefore constant across
every group of a fixed order, and within the genuine twin pairs all of the
coarse properties they study coincide --- though commutativity does vary across
the fifteen groups. The outcome varies by more than $0.9$ of accuracy.

This work varies the group at fixed order, dataset size and output cardinality.
The central instrument is the character-table twin: two groups whose ordinary
complex character tables are identical, so that essentially every coarse
invariant a network could plausibly be sensitive to --- number of conjugacy
classes, irreducible dimensions, commuting probability --- is matched by
construction. What differs is the real structure --- though not \emph{only} that: the twins
also differ in their power maps, involution counts, subgroup lattices and
element-order profiles, all of which a network can read off the Cayley table
(\S\ref{sec:threats}). For $D_8$ and $Q_8$,
\begin{equation}
\mathbb{R}[D_8] \cong \mathbb{R}^4 \oplus M_2(\mathbb{R}), \qquad
\mathbb{R}[Q_8] \cong \mathbb{R}^4 \oplus \mathbb{H}.
\end{equation}
Both $M_2(\mathbb{R})$ and $\mathbb{H}$ complexify to $M_2(\mathbb{C})$, which
is exactly why the ordinary character table cannot distinguish them. The
Frobenius--Schur indicator can, because it requires $\chi(g^2)$ --- the power
map --- which the character table as a matrix does not contain. Equivalently, the two differing simple blocks $M_2(\mathbb{R})$ and
$\mathbb{H}$ --- not the full semisimple algebras --- represent the two classes
of $\mathrm{Br}(\mathbb{R}) \cong \mathbb{Z}/2$.

\paragraph{Contributions.}
\begin{enumerate}
\item A matched-character-table design evaluated on the \emph{complete}
population of order-24 groups, which removes within-order group-selection
discretion (\S\ref{sec:setup}, \S\ref{sec:A}).
\item Evidence that representation type predicts validation accuracy at a
fixed data and training budget, stated at the correct unit of replication
(\S\ref{sec:A}).
\item A demonstration that the linear-probe gap depends on the probe, spanning
$0.256$ across recipes on a fixed representation and $0.179$ when only the
readout weight decay is varied, with a published protocol landing on the side
reporting no gap (\S\ref{sec:probe}).
\item A factorial separating two opposite roles of weight decay
(\S\ref{sec:wd}).
\item An exact isotypic decomposition of the output map, with transplantation
under a donor fixed in advance (\S\ref{sec:sector}).
\item A threats-to-validity section naming what the design does not isolate
(\S\ref{sec:threats}).
\end{enumerate}

\section{Setup}\label{sec:setup}

\paragraph{Task.} For a finite group $G$ with $|G| = n$, the model receives
$(g,h) \in G^2$ as the concatenation of two one-hot vectors in $\mathbb{R}^{2n}$
and predicts $gh$ as one of $n$ classes. All groups have $n = 24$, so the
dataset is 576 pairs and the output space is 24 classes in every condition. A
fraction $\rho$ of pairs is used for training and the remainder for validation.

\paragraph{Model and optimisation.} One hidden layer, width 512, ReLU, no
biases; full-batch AdamW, $\mathrm{lr} = 2\times10^{-3}$, $\beta = (0.9, 0.98)$,
weight decay $1.0$ unless swept, cross-entropy.

\paragraph{The population.} There are exactly fifteen groups of order 24 up to
isomorphism. The Small Groups Library lists fifteen isomorphism classes of
order 24; we construct fifteen pairwise non-isomorphic groups matching that
count, separated by a fingerprint combining element-order profile,
conjugacy-class sizes, isotypic sector types, centre order and
derived-subgroup order. Distinct fingerprints establish at least fifteen; the
upper bound is the classification result. Using the whole population removes
within-order group-selection discretion --- though not the choice of order 24,
of $\rho$, of budget, or of final accuracy as the outcome. Five carry quaternionic-type irreducible representations
--- $\mathrm{SL}(2,3)$, $\mathrm{Dic}_{24}$, $Q_8\times\mathbb{Z}_3$,
$\mathbb{Z}_2\times\mathrm{Dic}_{12}$ and $\mathbb{Z}_3\rtimes\mathbb{Z}_8$ ---
and there are exactly two character-table twin pairs.

Cayley tables are checked programmatically: unique identity, existence of
inverses, exhaustive associativity over all $24^3 = 13{,}824$ triples, and the
Frobenius--Schur identity
$\sum_\rho \varepsilon_\rho d_\rho = \#\{g : g^2 = e\}$.

\paragraph{Instances.} Each of the twelve instances per group draws an
independent random relabelling of the group, an independent train/validation
split and an independent initialisation. This separates three sources of
variance that a single seed would confound. With one-hot inputs, no biases and
i.i.d.\ initialisation, relabelling is a permutation of the coordinate axes and
is distributionally equivalent to resampling the split; we run it anyway as a
check on that argument.

\paragraph{Isotypic projectors.} At $\rho = 0.60$ the split is 345 training and
231 validation pairs; at $\rho = 0.70$ it is 403 and 173. Class sums span the
centre of $\mathbb{R}[G]$.
A random symmetric central element is scalar on each real isotypic component, so
its eigenspaces are those components; conjugate pairs of complex-type
irreducible representations merge, which is what a real network sees. Each
The Frobenius--Schur indicator of an irreducible character is
$\nu_\chi = |G|^{-1}\sum_g \chi(g^2) \in \{+1,0,-1\}$. The quantity we attach to
a real isotypic sector is $s = |G|^{-1}\sum_g \chi_S(g^2)$, where $\chi_S$ is the
character of that sector, so $s = d_\chi \nu_\chi$: it equals $+d$ for real type,
$0$ for a merged conjugate pair and $-d$ for quaternionic type. Idempotency, integer trace,
integer $s$ and $\sum_S P_S = I$ are asserted numerically at construction.
Consequently the logit decomposition $\ell = \sum_S P_S \ell$ is exact to
floating point rather than an attribution heuristic --- the property that
motivates using this task family at all.

\paragraph{Probe protocol.} The training split is divided into a fit set
(80\%) and a selection set (20\%), with an independent partition per run. The ridge strength is chosen on the selection set and the probe is then
refitted at that value on the whole training split; every other recipe is fixed
in advance and reported separately rather than selected. Validation accuracy is
logged through training so that learning curves can be drawn; it drives no
selection decision. Split, initialisation and probe partition use three
separate seed streams, so none is confounded with the others.

\paragraph{Batching.} Many runs are trained in one batched job. The
cross-entropy is multiplied by the number of runs so that each run's gradient
equals what it would be if that run were trained alone. Without this the loss
averages over $R \cdot N$ examples, every gradient is scaled by $1/R$, and
Adam's $\epsilon$ becomes an effective $R \cdot 10^{-8}$, comparable to
$\sqrt{v}$ once gradients are small --- exactly the phase these experiments
measure.

\section{Finding A: representation type predicts fixed-budget accuracy}\label{sec:A}

\subsection{The complete population}

\begin{figure}[t]\centering
\genfig{population.png}{\textwidth}
\caption{All fifteen groups of order 24 at $\rho = 0.60$, ranked by mean final
validation accuracy. Red bars carry quaternionic-type irreducible
representations. Dots are the twelve instances, each an independent relabelling,
split and initialisation. Four of the five red bars are the bottom four; the
five red bars are the bottom five with no inversion; the boundary is close, with
$\mathbb{Z}_2\times\mathrm{Dic}_{12}$ at $0.674$ sitting $0.011$ below
$\mathbb{Z}_2\times A_4$ at $0.685$.}
\label{fig:pop}
\end{figure}


Figure~\ref{fig:pop} and Table~\ref{tab:pop} give final validation accuracy at $\rho = 0.60$ after 9k
epochs, twelve instances per group, all fifteen groups of order 24.

\begin{table}[t]\centering\small
\begin{tabular}{rlrrrrl}
\toprule
rank & group & q-mass & mean & sd & min & \\
\midrule
1 & $\mathrm{SL}(2,3)$ & 0.1667 & 0.075 & 0.028 & 0.026 & quaternionic\\
2 & $\mathrm{Dic}_{24}$ & 0.5000 & 0.198 & 0.055 & 0.108 & quaternionic\\
3 & $Q_8\times\mathbb{Z}_3$ & 0.1667 & 0.271 & 0.038 & 0.208 & quaternionic\\
4 & $\mathbb{Z}_3\rtimes\mathbb{Z}_8$ & 0.1667 & 0.339 & 0.059 & 0.242 & quaternionic\\
5 & $\mathbb{Z}_2\times\mathrm{Dic}_{12}$ & 0.3333 & 0.674 & 0.031 & 0.619 & quaternionic\\
6 & $\mathbb{Z}_2\times A_4$ & 0 & 0.685 & 0.027 & 0.628 & \\
7 & $S_4$ & 0 & 0.699 & 0.029 & 0.649 & \\
8 & $D_8\times\mathbb{Z}_3$ & 0 & 0.739 & 0.040 & 0.684 & \\
9 & $\mathbb{Z}_3\rtimes D_8$ & 0 & 0.776 & 0.041 & 0.706 & \\
10 & $\mathbb{Z}_4\times S_3$ & 0 & 0.804 & 0.043 & 0.710 & \\
11 & $\mathbb{Z}_{24}$ & 0 & 0.995 & 0.004 & 0.987 & \\
12 & $\mathbb{Z}_6\times\mathbb{Z}_2^2$ & 0 & 0.996 & 0.009 & 0.970 & \\
13 & $\mathbb{Z}_{12}\times\mathbb{Z}_2$ & 0 & 0.998 & 0.004 & 0.987 & \\
14 & $D_{24}$ & 0 & 0.999 & 0.002 & 0.996 & \\
15 & $\mathbb{Z}_2\times D_{12}$ & 0 & 0.999 & 0.003 & 0.991 & \\
\bottomrule
\end{tabular}
\caption{All fifteen groups of order 24, $\rho = 0.60$, 9k epochs, twelve
instances each. q-mass is the fraction of the regular representation carried by
quaternionic-type sectors. Chance is $1/24 = 0.042$.}
\label{tab:pop}
\end{table}

\subsection{Statistics, at the correct unit}

The unit of replication is the group. Instances resample the same fifteen tasks;
quoting instance counts would be pseudoreplication.

The preregistered primary test is the exact ordering statistic: that the five
quaternionic-type groups occupy the bottom five positions. They do, with no
inversion. Their rank sum is 15, the minimum attainable, and the worst
non-quaternionic group ($\mathbb{Z}_2\times A_4$ at $0.685$) sits above the best
quaternionic group ($\mathbb{Z}_2\times\mathrm{Dic}_{12}$ at $0.674$). Under
exchangeability of the fifteen groups,
\begin{equation}
\Pr(\text{the five occupy the bottom five}) = \binom{15}{5}^{-1}
= \tfrac{1}{3003} = 3.3\times10^{-4}.
\end{equation}
The preregistered secondary analysis, an exact permutation test on group means
over all 3003 labellings, gives $p = 3.3\times10^{-4}$ with a difference in
means of $+0.558$.

Two caveats. Eight of the fifteen groups are the ones on which the hypothesis
was formed, so this is a preregistered extension to the complete population
rather than a wholly prospective confirmation; the genuinely unseen content is
the seven new groups, of which the two quaternionic ones
($\mathbb{Z}_2\times\mathrm{Dic}_{12}$ and
$\mathbb{Z}_3\rtimes\mathbb{Z}_8$) both landed in the bottom five as predicted.
And the margin at the boundary is $0.011$, about a third of the within-group
standard deviation there, so the ordering is exact but not comfortable.

Between-group variance is $0.101$ and within-group variance $0.0011$, a ratio
of $92$, where an instance varies relabelling, split and initialisation
independently. Under this protocol, variation from those three sources is much
smaller than variation between groups. This is a descriptive comparison of two
sample variances, not a fitted variance-components decomposition.

\subsection{Twin pairs}

\begin{figure}[t]\centering
\genfig{twins.png}{0.85\textwidth}
\caption{The two verified character-table twin pairs, and one degree- and
class-size-matched contrast that is not a twin. Within a twin pair the ordinary
complex character table is identical; the Frobenius--Schur indicator differs,
along with the power map and everything else it determines.}
\label{fig:twinfig}
\end{figure}


\begin{table}[t]\centering\small
\begin{tabular}{lrrrr}
\toprule
pair & non-quaternionic & quaternionic & $\Delta$ & Welch $t$\\
\midrule
$D_8\times\mathbb{Z}_3$ / $Q_8\times\mathbb{Z}_3$ & 0.739 & 0.271 & $+0.469$ & 29.3\\
$D_{24}$ / $\mathrm{Dic}_{24}$ & 0.999 & 0.198 & $+0.801$ & 50.7\\
\midrule
\emph{$\mathbb{Z}_2\times D_{12}$ / $\mathbb{Z}_2\times\mathrm{Dic}_{12}$ (not a twin)} & 0.999 & 0.674 & $+0.325$ & 35.7\\
\bottomrule
\end{tabular}
\caption{The two character-table twin pairs at order 24 (top), and one
degree- and class-size-matched contrast that is \emph{not} a twin (bottom,
italicised). Within a twin pair the ordinary complex character table is
identical; $\mathbb{Z}_2\times D_{12}$ and $\mathbb{Z}_2\times\mathrm{Dic}_{12}$
differ in their linear characters. $\rho = 0.60$.}
\label{tab:twins}
\end{table}

Table~\ref{tab:twins} and Figure~\ref{fig:twinfig} are the controlled
contrast and the rank-sum test is not: comparing $\mathbb{Z}_{24}$ to $S_4$
compares two tasks that differ in everything.

There are exactly two character-table twin pairs at order 24, and both are among
the groups on which the hypothesis was formed. They are therefore descriptive
evidence, not a prospective test, and we report no sign test over them. The
third row of Table~\ref{tab:twins} is a weaker contrast, matched on the
multiset of irreducible degrees and the multiset of conjugacy-class sizes but
\emph{not} on the character table: $\mathbb{Z}_2\times\mathrm{Dic}_{12}$ has
abelianisation $\mathbb{Z}_2\times\mathbb{Z}_4$ and hence four linear
characters taking the values $\pm i$, while every linear character of
$\mathbb{Z}_2\times D_{12}$ is real. It was preregistered and had never been
trained, and it separates in the predicted direction, but it does not replicate
the twin design. Improving on two twin pairs requires other orders.


\begin{figure}[t]\centering
\includegraphics[width=0.8\textwidth]{../figs/fig10_dose_response.png}
\caption{Dose--response on the original eight-group grid, two seeds, fixed 9k
budget. Solid: no quaternionic sector. Dashed: quaternionic. The separation widens as $\rho$ falls. In this released grid the
quaternionic groups reach only $0.61$--$0.66$ at $\rho = 0.70$ and no run
crosses the $0.90$ generalisation threshold, so these data show a higher data
requirement but do not by themselves show that the tasks become easy at higher
$\rho$. Produced by the original
codebase from \texttt{results/dose\_response.json}.}
\label{fig:dose}
\end{figure}

\subsection{q-mass is not a dose}

Figure~\ref{fig:dose} shows the same effect as a dose--response on the original
eight-group grid: the separation is in the training fraction required, not in
learnability. The fraction of the regular representation carried by quaternionic
sectors takes four values here. Mean accuracy by level is $0.869$ ($q = 0$), $0.228$ ($1/6$), $0.674$ ($1/3$),
$0.198$ ($1/2$): correlation $-0.697$, not monotone. This
prediction was preregistered as risky and it failed. The presence of a
quaternionic sector predicts the sign of the effect; q-mass does not scale it.

\section{Finding B: what a linear-probe gap measures}\label{sec:probe}

\begin{figure}[t]\centering
\genfig{two_speeds.png}{\textwidth}
\caption{Two speeds, on the character-table twins. Grey is training accuracy,
red the native readout on held-out data, blue a ridge probe fitted to the frozen
hidden layer on the training split only with $\lambda$ chosen inside that split.
Three seeds each, $\rho = 0.70$, log epoch axis. In both groups the probe reaches
ceiling long before the native readout does. In $D_8\times\mathbb{Z}_3$ the
native readout catches up; in $Q_8\times\mathbb{Z}_3$ it does not, and the two
curves stay separated for the rest of training. Generated by
\texttt{analyse.py} from \texttt{results/e3\_probe\_protocol.json}.}
\label{fig:twospeeds}
\end{figure}


Chou et al.\ \cite{chou} decompose a network into encoder and linear readout and
define a sub-optimal-readout signature: linear-probe accuracy substantially
exceeding model accuracy, indicating that the readout under-performs relative to
what the encoder affords. They demonstrate it on permutation composition in
$S_5$ on an MLP. The existence of such a gap is therefore not new.

Figure~\ref{fig:twospeeds} shows the dynamics: in both twins the probe reaches ceiling long before the native readout, and in $Q_8\times\mathbb{Z}_3$ the native readout never closes the distance. That a probe's verdict depends on its capacity and regularisation is not itself
new; it is the central point of the probing-control literature
\cite{hewitt,pimentel}. What has not been examined is how much this particular
grokking diagnostic depends on it.
Table~\ref{tab:probes} reports nine non-redundant settings of the thirty
readout configurations that \texttt{e3\_probe\_protocol.py} fits to \emph{one
unchanged} frozen $Q_8\times\mathbb{Z}_3$ representation at $\rho = 0.70$: two
Chou budgets, seven AdamW weight decays from a fresh initialisation, the same
seven from the native readout, thirteen closed-form ridge strengths, and ridge
with $\lambda$ selected inside the training split. Every configuration reaches
training accuracy $1.000$ on the split it was fitted to: they all interpolate
and differ only in which interpolating readout they select. Within a seed every
recipe sees the same frozen representation; the three seeds are three separately
trained representations and the table reports their mean.

\begin{table}[t]\centering\small
\begin{tabular}{lrr}
\toprule
readout recipe & $Q_8\times\mathbb{Z}_3$ gap & $D_8\times\mathbb{Z}_3$ gap\\
\midrule
AdamW, wd 1.0, 200 epochs \cite{chou} & $-0.021$ & $-0.079$\\
AdamW, wd 1.0, 4000 epochs & $+0.008$ & $+0.000$\\
AdamW, wd 1.0, 4000 epochs, lr $2\times10^{-3}$ & $+0.002$ & $+0.000$\\
AdamW, wd 0.3 & $+0.033$ & $+0.013$\\
AdamW, wd 0.1 & $+0.125$ & $+0.025$\\
AdamW, wd 0.03 & $+0.170$ & $+0.027$\\
AdamW, wd 0.01 & $+0.181$ & $+0.027$\\
AdamW, wd 0 & $+0.177$ & $+0.027$\\
ridge, $\lambda$ chosen inside train & $+0.235$ & $-0.033$\\
\bottomrule
\end{tabular}
\caption{Probe accuracy minus native accuracy, one frozen representation, three
seeds, $\rho = 0.70$. Training accuracy is $1.000$ for every recipe. The top row
is the protocol of \cite{chou}, Appendix A.1.3. Every recipe is fitted on the
model's full training split, the same data the native readout saw.}
\label{tab:probes}
\end{table}

\begin{figure}[t]\centering
\genfig{probe_families.png}{0.8\textwidth}
\caption{Probe accuracy minus native accuracy on one frozen representation that
never changes, by readout recipe. Every recipe reaches training accuracy
$1.000$. \texttt{chou\_200} is the protocol of \cite{chou} verbatim; it reports a
negative gap, and the twins do not separate under it. \texttt{ridge\_cv} reports
$+0.235$ and separates them.}
\label{fig:probefam}
\end{figure}


The reported gap spans $0.256$ (Figure~\ref{fig:probefam}). The endpoints
differ in objective, optimiser, budget and initialisation as well as in
regularisation, so this span measures sensitivity to the probe protocol as a
whole; the clean regularisation-only contrast is the $0.179$ span of
\S\ref{sec:wd}, at a fixed representation and a fixed fitting procedure. Under
the protocol of the paper that defines the
signature --- AdamW, $\mathrm{lr}\,10^{-3}$, weight decay $1.0$, 200 full-batch
epochs, justified there as ensuring that high probe accuracy reflects genuinely
structured representations rather than memorisation --- $Q_8\times\mathbb{Z}_3$
reports $-0.021$, and at that weight decay run to convergence it reports
$+0.002$: no readout defect. The character-table twins are also
indistinguishable there ($+0.002$ against $+0.000$; three seeds, no equivalence
test, so this is a failure to separate rather than a demonstration of
equality). Under ridge with $\lambda$ chosen inside the training split and
refitted on all of it, the same frozen features give $+0.235$ against $-0.033$
and the twins separate. The decisive comparison is the weight decay itself:
at $\lambda_{\mathrm{probe}} = 1.0$ the gap is $+0.002$ and at
$\lambda_{\mathrm{probe}} = 0.01$ it is $+0.181$, with objective, optimiser,
budget and initialisation all held fixed.

We do not claim that the weakly regularised readout is the ``true'' capability
of the representation. A probe is always a measurement relative to a hypothesis
class and an inductive bias, and \cite{chou} may reasonably intend to measure
only especially accessible structure. The claim is narrower and, we think,
unavoidable: \emph{the linear-probe gap is not well defined without stating the
probe's regularisation}, and in this family the choice moves the reported value
by more than a third of the accuracy range, including across zero and including
the presence or absence of a twin-pair difference.

\paragraph{Is this regime spurious?} Chou et al.\ retire a published grokking
example as spurious using a representation-degradation signature: probe accuracy
falling while critical dimension rises, under a recipe that actively degrades
representation quality. A referee will aim that at weight decay $1.0$ at
sub-critical $\rho$. We therefore run their discriminant on ourselves. Probe
accuracy rises from near zero to $0.994$--$1.000$ through training in every run
and effective representation rank rises with it ($57$--$60$ to $69$--$71$), so
the degradation signature is absent in all six runs. The sub-optimal-readout
signature is present in all three $Q_8\times\mathbb{Z}_3$ seeds and in one of
three $D_8\times\mathbb{Z}_3$ seeds, so it is not cleanly absent in the grokking
twin, only much rarer and much smaller.

\section{Weight decay has two roles}\label{sec:wd}

\begin{table}[t]\centering\small
\begin{tabular}{lrrrrrr}
\toprule
& \multicolumn{6}{c}{$\lambda_{\mathrm{readout}}$}\\
\cmidrule(l){2-7}
$\lambda_{\mathrm{train}}$ & 0 & 0.01 & 0.1 & 0.3 & 1 & 3\\
\midrule
0 & 0.013 & 0.012 & 0.012 & 0.002 & 0.002 & 0.000\\
0.01 & 0.023 & 0.015 & 0.013 & 0.006 & 0.000 & 0.000\\
0.1 & 0.276 & 0.266 & 0.150 & 0.143 & 0.123 & 0.044\\
0.3 & 0.798 & 0.796 & 0.736 & 0.586 & 0.539 & 0.561\\
1 & 0.879 & 0.881 & 0.842 & 0.761 & 0.734 & 0.765\\
3 & 0.821 & 0.815 & 0.769 & 0.667 & 0.640 & 0.672\\
\bottomrule
\end{tabular}
\caption{$Q_8\times\mathbb{Z}_3$, $\rho = 0.70$, mean of three seeds --- three
independently trained representations, not one. Validation
accuracy of a readout refitted on the frozen hidden layer, crossing the weight
decay used end to end with the weight decay used in the refit.}
\label{tab:factorial}
\end{table}

\begin{figure}[t]\centering
\genfig{wd_factorial.png}{\textwidth}
\caption{Left and centre: native and probe accuracy against end-to-end weight
decay, reported separately rather than as a difference, because the probe
ceiling moves. Right: the refit accuracy of Table~\ref{tab:factorial} as a
heatmap. Variation down the rows (training decay) is much larger than variation
across the columns (refit decay), and the two act in opposite directions.}
\label{fig:wd}
\end{figure}


Figure~\ref{fig:wd} plots the same data. An earlier version of this work titled this section ``the obstruction is weight
decay''. The factorial in Table~\ref{tab:factorial} shows that phrase conflates
two effects of opposite sign.

Read down the first column: as $\lambda_{\mathrm{train}}$ goes $0 \to 1$, the
best achievable refit goes $0.013 \to 0.879$, a span of $0.865$. Probe accuracy
on the frozen layer goes $0.162 \to 0.992$ over the same range. Training weight
decay is \emph{associated with} greater linear decodability at this fixed
budget; at
$\lambda_{\mathrm{train}} = 0$ there is nothing to express, and a probe--native
difference measured there is a difference between two numbers near chance, not
an unexpressed computation. For this reason we report native and probe accuracy
as separate columns throughout and do not compare their difference across
$\lambda_{\mathrm{train}}$: the probe ceiling moves.

Read across the $\lambda_{\mathrm{train}} = 1$ row: the refit goes
$0.879 \to 0.734$, a span of $0.146$, on a representation that does not change.
Readout weight decay is what \emph{limits expression}. At
$\lambda_{\mathrm{train}} = 1$ the native readout reaches $0.730$; refitting at
the training decay recovers $+0.004$, and refitting at zero recovers $+0.148$.
The same contrast in the grokking twin $D_8\times\mathbb{Z}_3$ is $+0.002$ and
$+0.023$ from a native $0.975$: there is little to recover when the readout is
already expressing what the representation supports.
Training accuracy is $1.000$ in every cell: the representation is separable,
many readouts interpolate the training split, and they generalise very
differently.

Across this grid, variation associated with training decay is substantially
larger than variation associated with refit decay, and the two interact. We do
not quote a ratio: the two spans are endpoint differences along one selected
column and one selected row, so their quotient is descriptive geometry of this
table rather than a factorial effect estimate. What matters is that both effects
are real, they act in opposite directions, and a single unqualified statement
about ``weight decay'' cannot describe them. This cuts against the standard account
\cite{power,nanda,varma} --- in which weight decay is the ingredient that causes
grokking --- only in the sense that the same term at the same strength does two
things at two places in the network.

We have not established that the column effect is not a logit-scale effect.
Truong \cite{truong} shows that under cross-entropy the weight-norm dependence
of the grokking delay collapses onto the effective logit scale ($R^2 = 0.97$,
with the norm dose adding 1--2\%), and that shifting norm mass toward the readout
at fixed total norm changes the delay by $1.7$--$2.2\times$. Our dependent
variable is different --- expression at a fixed budget rather than delay --- and
the direction is opposite, since higher weight decay lowers the norm and hence
the logit scale. Whether the column effect collapses onto the realised logit
scale is a preregistered open question; the logit scale is logged at every
checkpoint and the regression is outstanding.

\section{Sector localisation is partial}\label{sec:sector}

Writing $W_2 = \sum_S P_S W_2$ exactly, we transplant a single sector's readout
block between the native and refitted output maps, holding $W_1$ frozen so there
is no basis-alignment confound. The donor is fixed in advance
($\lambda_{\mathrm{readout}} = 0$, native initialisation). An earlier version
selected the donor by validation accuracy over eight configurations, which is
selection on the reported metric; that result does not survive the fixed donor.

\begin{table}[t]\centering\small
\begin{tabular}{lrrrr}
\toprule
sector & native $+$ repaired & sufficiency & repaired $+$ native & necessity\\
\midrule
trace-8 complex pair & 0.809 & 50.0\% & 0.827 & 37.8\%\\
trace-4 Frobenius--Schur-typed & 0.825 & 60.8\% & 0.817 & 44.6\%\\
group-equivariant rank 8 & 0.738 & 0.0\% & 0.875 & 4.1\%\\
random rank 8 & 0.119 & --- & 0.089 & ---\\
\bottomrule
\end{tabular}
\caption{$Q_8\times\mathbb{Z}_3$, mean of three independently trained
representations, native $0.738$, repaired $0.881$.
Sufficiency and necessity are fractions of the $0.143$ repair range. A random
rank-8 subspace of $\mathbb{R}^{24}$ is not group-equivariant and cuts across
every isotypic component, so it destroys any working readout; it is shown for
scale, not as a control.}
\label{tab:sector}
\end{table}

In Table~\ref{tab:sector} the two algebraically meaningful sectors carry
comparable amounts and neither dominates; the difference between them is within
three-seed noise. In the grokking twin the whole repair range is $0.031$, too
small for the fractions to carry meaning, so no localisation is claimed there. The
group-equivariant control carries almost nothing, so the effect is not generic
to any rank-8 equivariant subspace. This is weaker and less specific than an
earlier version of this work claimed. It is localisation, not explanation.

One quantity is uninformative and we exclude it. The per-sector relative change
$\|P_S(W_2^{\mathrm{rep}} - W_2^{\mathrm{nat}})\| / \|P_S W_2^{\mathrm{nat}}\|$
reads $18$--$32\times$ for one one-dimensional sector in every run. This is
division by noise: cross-entropy is invariant to a constant shift of all logits,
so that direction is unconstrained and the denominator is near zero.

\section{The trace-8 account does not explain Finding A}

Neither $D_{24}$ nor $\mathrm{Dic}_{24}$ possesses a trace-8 sector; all their
isotypic sectors are trace 1 or trace 4. The readout defect of
\S\ref{sec:probe} therefore cannot operate through that sector in that pair,
yet the accuracy separation appears there anyway, with three times the
Frobenius--Schur contrast. This rules out one specific route between the two
findings. It does not establish that they are independent: Finding B has not
been measured in the $D_{24}$ pair at all, and the trace-4 sector remains a
plausible common mechanism.

A further obstacle to any unifying account: the Frobenius--Schur distinction
lives in the trace-4 sector, and for $D_8\times\mathbb{Z}_3$ and
$Q_8\times\mathbb{Z}_3$ the trace-8 sectors are isomorphic as real algebras
(both $M_2(\mathbb{C})$, being the 2-dimensional irreducible representation
tensored with the nontrivial cube roots of unity). Under the fixed donor the
trace-4 sector now carries at least as much of the repair as the trace-8 sector,
which weakens this obstacle but does not remove it, since the two are within
noise of each other. Any mechanism proposed for (B) must address it.

\section{Threats to validity}\label{sec:threats}

\paragraph{Character-table twins do not isolate Frobenius--Schur type.} They
match the ordinary complex character table. They do not match the power map, the
involution count, the subgroup lattice, the automorphism structure or the
element-order profile, all of which a network can read off the Cayley table.
Involution count is the live competitor: $D_{24}$ has 13 and
$\mathrm{Dic}_{24}$ has 1, so it is anti-correlated with quaternionic type on
these pairs by construction. The correct claim is that Frobenius--Schur type is
a candidate predictor in the tested population, not an isolated cause.
Separating the candidates requires an out-of-sample predictive comparison
against the competing invariants, which is outstanding.

\paragraph{Sample size.} Fifteen groups is fifteen groups, and one order. Two twin
pairs is two, and there are no more at order 24. Twelve instances per
group shrink within-group variance but do not increase $n$ at the group level.

\paragraph{Preregistered predictions that failed.} Monotonicity in q-mass
failed, and the identity of the interfering sector was not predicted in
advance. These are
recorded with their outcomes in the repository's preregistration file. Two
further predictions --- the alternative-predictor comparison and the
logit-scale regression --- have not yet been run.

\paragraph{Post-hoc sector selection.} The interfering sector was identified by
scanning all sectors and reporting the one that repaired. That selection is
post-hoc. $\mathrm{SL}(2,3)$ replicates a repair with a \emph{different} sector,
which is honest evidence that which sector interferes is not yet predictable a
priori. Until it is, no preregistered prediction of the sector identity is
possible, and this remains the largest outstanding weakness in (B).

\paragraph{Single architecture.} One-hidden-layer MLP, one optimiser, one
recipe. A TransformerLens port trains but had not converged on the harder groups
at the budgets tested; no architecture-transfer claim is made.

\paragraph{Validation set size.} 173 examples at $\rho = 0.70$ and 231 at
$\rho = 0.60$. Precision is limited accordingly.

\paragraph{Budget censoring.} Non-generalising entries are lower bounds at the
stated budget. Censoring at a single training fraction conflates ``does not
generalise'' with ``is below the critical dataset size''; the dense $\rho$ sweep
that would resolve this is outstanding.

\section{Planned work}

Each with a preregistered gate --- the outcome that would falsify it --- because
the value of this task family is that such gates are cheap.

\begin{enumerate}
\item \textbf{Does q-mass beat the alternatives out of sample?}
Leave-one-group-out prediction of mean accuracy from q-mass against involution
count, exponent, centre order, abelianisation, class count, largest irreducible
dimension, commuting probability and element-order profile. \emph{Gate:} if
involution count matches it, the claim narrows to ``a power-map statistic
predicts sample complexity'', with Frobenius--Schur type one such statistic
among several.
\item \textbf{Does the expression gap collapse onto the logit scale?} Regress the
gap on the realised logit scale, then add $\lambda_{\mathrm{readout}}$.
\emph{Gate:} if the increment in $R^2$ is below $0.10$, the readout defect
belongs to \cite{truong} rather than here.
\item \textbf{Other orders.} Order 16 has character-table twins, as does order
48. \emph{Gate:} if the twin separation does not replicate at another order, the
effect is order-24-specific.
\item \textbf{Predict the interfering sector before running.} Formulate a rule
from the $Q_8\times\mathbb{Z}_3$, $D_8\times\mathbb{Z}_3$ and
$\mathrm{SL}(2,3)$ cases and preregister it on a held-out group. \emph{Gate:} a
wrong prediction retires the sector-level account and leaves the readout-level
one, which is fine.
\item \textbf{Architecture transfer.} Train a transformer to convergence on the
same task and measure the probe families. \emph{Gate:} no transfer means the
finding is MLP-specific. Lower priority than 1--4, because a mechanism should be
understood before it is chased across architectures.
\end{enumerate}

\paragraph{Deliberately not attempted.} Constructing semisimple algebras
$\mathbb{R}^4 \oplus \mathbb{C}^4 \oplus M_2(\mathbb{R}) \oplus M_2(\mathbb{C})$
versus $\mathbb{R}^4 \oplus \mathbb{C}^4 \oplus \mathbb{H} \oplus
M_2(\mathbb{C})$ to isolate the Brauer class directly would be the cleanest
possible test of (A). We do not attempt it here: basis elements of a general
semisimple algebra are not closed under multiplication, so the task becomes
structure-tensor regression rather than classification, changing the loss, the
output format and plausibly the learning dynamics. It is a separate study, not
an extension of this one.

\section{Scope}

This is a controlled algebraic testbed, not a claim about frontier models.
Interpretability of small models on algorithmic tasks is a mature area in which
the bar for a novel contribution is high, and nothing here should be assumed to
transfer. What the setting buys is exactness: the projectors come from the
Cayley table, sum to the identity, and make the decomposition verifiable to
floating point rather than arguable. Settings in which a mechanistic claim can be
verified rather than defended are rare.

The transferable question, if there is one, concerns measurement. A model can
contain a computation that its own output map does not express. Whether a probe
reports that depends on how the probe is regularised --- by $0.256$ of accuracy
here across recipes, and $0.179$ varying the regulariser alone, with a published
protocol landing on the side that reports no defect and losing the twin-pair
distinction with it.
Distinguishing capability absent from capability present but unexpressed matters
for evaluation and elicitation, and it cannot be done with an unspecified probe.

\begin{thebibliography}{9}
\bibitem{power} A. Power, Y. Burda, H. Edwards, I. Babuschkin, V. Misra.
\emph{Grokking: Generalization Beyond Overfitting on Small Algorithmic
Datasets.} arXiv:2201.02177, 2022.
\bibitem{nanda} N. Nanda, L. Chan, T. Lieberum, J. Smith, J. Steinhardt.
\emph{Progress Measures for Grokking via Mechanistic Interpretability.} ICLR
2023. arXiv:2301.05217.
\bibitem{chughtai} B. Chughtai, L. Chan, N. Nanda. \emph{A Toy Model of
Universality: Reverse Engineering How Networks Learn Group Operations.} ICML
2023.
\bibitem{stander} D. Stander, Q. Yu, H. Fan, S. Biderman. \emph{Grokking Group
Multiplication with Cosets.} ICML 2024. arXiv:2312.06581.
\bibitem{varma} V. Varma, R. Shah, Z. Kenton, J. Kram\'ar, R. Kumar.
\emph{Explaining Grokking Through Circuit Efficiency.} arXiv:2309.02390, 2023.
\bibitem{chou} C.-N. Chou, O. Uzdelewicz, N.-C. Chiu, Y.-Y. Yang, S. Chung.
\emph{Two Speeds of Learning: A Representation--Readout Decomposition of
Grokking and Double Descent.} arXiv:2605.27078, 2026.
\bibitem{notsawo} P. J. Tikeng Notsawo, G. Dumas, G. Rabusseau. \emph{Grokking
Finite-Dimensional Algebra.} ICML 2026. arXiv:2602.19533.
\bibitem{hewitt} J. Hewitt, P. Liang. \emph{Designing and Interpreting Probes
with Control Tasks.} EMNLP 2019.
\bibitem{pimentel} T. Pimentel, R. Cotterell et al. \emph{Probing as
Quantifying Inductive Bias.} ACL 2022.
\bibitem{truong} X. K. Truong. \emph{What Does the Weight Norm Control in
Grokking? Logit-Scale Mediation under Cross-Entropy.} arXiv:2606.18465, 2026.
\end{thebibliography}

\end{document}
